/*
 Copyright and licenses see https://www.dynatrace.com/company/trust-center/customers/reports/ */
(function(){function Ia(){document.cookie="".concat("__dTCookie","=").concat("1",";SameSite=Lax");var Oa=document.cookie.includes("__dTCookie");document.cookie="".concat("__dTCookie","=").concat("1","; expires=Thu, 01-Jan-1970 00:00:01 GMT");return Oa}function fb(){return void 0===bb.dialogArguments?navigator.cookieEnabled||Ia():Ia()}function nb(){var Oa;if(fb()){var Pa=bb.dT_,Za=null===Pa||void 0===Pa?void 0:Pa.platformPrefix;if(!Pa||Za){var Qa=null===Pa||void 0===Pa?void 0:Pa.minAgentVersion;Qa&&
"10297240712040816"<Qa+""?window.console.log("[CookiePrefix/initConfig] Min agent version detected, and javascript agent is older - the javascript agent will not be initialized!"):(Qa=(Oa={},Oa.cfg="app=1e2ad11c943f2473|cors=1|owasp=1|featureHash=A7NVfqrux|reportUrl=https://bf52150pnj.bf.dynatrace.com/bf|rdnt=1|uxrgce=1|cuc=x7i7h154|mel=100000|expw=1|dpvc=1|lastModification=1753865417910|tp=500,50,0|agentUri=https://js-cdn.dynatrace.com/jstag/161f5a57e21/ruxitagent_A7NVfqrux_10297240712040816.js|auto=0|domain=|rid=RID_|rpid=|app=1e2ad11c943f2473",Oa.iCE=fb,Oa.platformCookieOffset=null===Pa||void 0===Pa?void 0:Pa.platformCookieOffset,Oa),Za&&(Qa.platformPrefix=Za),bb.dT_=Qa)}}}this.dT_&&dT_.prm&&dT_.prm();var bb="undefined"!==typeof globalThis?globalThis:
"undefined"!==typeof window?window:void 0,gb;"documentMode"in document&&!isNaN(document.documentMode)||(bb.dT_&&!bb.dT_.platformPrefix?bb.dT_.gCP||(null===(gb=bb.console)||void 0===gb?void 0:gb.log("Duplicate agent injection detected, turning off redundant initConfig."),bb.dT_.di=1):nb())})();
(function(){function Ia(g,q,w){if(w||2===arguments.length)for(var S=0,G=q.length,sa;S<G;S++)!sa&&S in q||(sa||(sa=Array.prototype.slice.call(q,0,S)),sa[S]=q[S]);return g.concat(sa||Array.prototype.slice.call(q))}function fb(g){var q;return function(){if(q)return q;var w,S,G,sa,Ib=-1!==bg?bg:(null===(S=null===(w=Wa.dT_)||void 0===w?void 0:w.scv)||void 0===S?void 0:S.call(w,"postfix"))||(null===(sa=null===(G=Wa.dT_)||void 0===G?void 0:G.gCP)||void 0===sa?void 0:sa.call(G));return q=w=(bg=Ib)?"".concat(g).concat(Ib):
g}}function nb(){var g=0;try{g=Math.round(Wa.performance.timeOrigin)}catch(q){}if(0>=g||isNaN(g)||!isFinite(g)){Xe.push({severity:"Warning",type:"ptoi",text:"performance.timeOrigin is invalid, with a value of [".concat(g,"]. Falling back to performance.timing.navigationStart")});g=0;try{g=Wa.performance.timing.navigationStart}catch(q){}g=0>=g||isNaN(g)||!isFinite(g)?vf:g}qe=g;Be=bb;return qe}function bb(){return qe}function gb(){return Be()}function Oa(){var g,q=0;if(null===(g=null===Wa||void 0===
Wa?void 0:Wa.performance)||void 0===g?0:g.now)try{q=Math.round(Wa.performance.now())}catch(w){}return 0>=q||isNaN(q)||!isFinite(q)?(new Date).getTime()-Be():q}function Pa(){var g;return!(null===(g=Wa.console)||void 0===g||!g.log)}function Za(g,q){if(!q)return"";var w=g+"=";g=q.indexOf(w);if(0>g)return"";for(;0<=g;){if(0===g||" "===q.charAt(g-1)||";"===q.charAt(g-1))return w=g+w.length,g=q.indexOf(";",g),0<=g?q.substring(w,g):q.substring(w);g=q.indexOf(w,g+w.length)}return""}function Qa(g){return Za(g,
document.cookie)}function $a(){}function Ka(g,q){void 0===q&&(q=document.cookie);return Za(g,q)}function xb(){}function Ca(g,q){return function(){g.apply(q,arguments)}}function fa(g){if(!(this instanceof fa))throw new TypeError("Promises must be constructed via new");if("function"!==typeof g)throw new TypeError("not a function");this.oa=0;this.qc=!1;this.sa=void 0;this.Ia=[];Na(g,this)}function oa(g,q){for(;3===g.oa;)g=g.sa;0===g.oa?g.Ia.push(q):(g.qc=!0,fa.Hb(function(){var w=1===g.oa?q.Oe:q.Pe;
if(null===w)(1===g.oa?ab:ua)(q.promise,g.sa);else{try{var S=w(g.sa)}catch(G){ua(q.promise,G);return}ab(q.promise,S)}}))}function ab(g,q){try{if(q===g)throw new TypeError("A promise cannot be resolved with itself.");if(q&&("object"===typeof q||"function"===typeof q)){var w=q.then;if(q instanceof fa){g.oa=3;g.sa=q;V(g);return}if("function"===typeof w){Na(Ca(w,q),g);return}}g.oa=1;g.sa=q;V(g)}catch(S){ua(g,S)}}function ua(g,q){g.oa=2;g.sa=q;V(g)}function V(g){2===g.oa&&0===g.Ia.length&&fa.Hb(function(){g.qc||
fa.vc(g.sa)});for(var q=0,w=g.Ia.length;q<w;q++)oa(g,g.Ia[q]);g.Ia=null}function X(g,q,w){this.Oe="function"===typeof g?g:null;this.Pe="function"===typeof q?q:null;this.promise=w}function Na(g,q){var w=!1;try{g(function(S){w||(w=!0,ab(q,S))},function(S){w||(w=!0,ua(q,S))})}catch(S){w||(w=!0,ua(q,S))}}function Ma(){ae.Hb=function(g){if("string"===typeof g)throw Error("Promise polyfill called _immediateFn with string");g()};ae.vc=function(){};return ae}function Z(g,q){var w;void 0===q&&(q=[]);if(!g||
"object"!==typeof g&&"function"!==typeof g)return!1;var S="number"!==typeof q?q:[],G=null,sa=[];switch("number"===typeof q?q:5){case 1:G="Boolean";break;case 2:G="Number";break;case 3:G="String";break;case 4:G="Function";break;case 5:G="Object";break;case 6:G="Date";sa.push("getTime");break;case 7:G="Error";sa.push("name","message");break;case 8:G="Element";break;case 9:G="HTMLElement";break;case 10:G="HTMLImageElement";sa.push("complete");break;case 11:G="PerformanceEntry";break;case 12:G="PerformanceTiming";
break;case 13:G="PerformanceResourceTiming";break;case 14:G="PerformanceNavigationTiming";break;case 15:G="CSSRule";sa.push("cssText","parentStyleSheet");break;case 16:G="CSSStyleSheet";sa.push("cssRules","insertRule");break;case 17:G="Request";sa.push("url");break;case 18:G="Response";sa.push("ok","status","statusText");break;case 19:G="Set";sa.push("add","entries","forEach");break;case 20:G="Map";sa.push("set","entries","forEach");break;case 21:G="Worker";sa.push("addEventListener","postMessage",
"terminate");break;case 22:G="XMLHttpRequest";sa.push("open","send","setRequestHeader");break;case 23:G="SVGScriptElement";sa.push("ownerSVGElement","type");break;case 24:G="HTMLMetaElement";sa.push("httpEquiv","content","name");break;case 25:G="HTMLHeadElement";break;case 26:G="ArrayBuffer";break;case 27:G="ShadowRoot",sa.push("host","mode")}q=G;if(!q)return!1;sa=sa.length?sa:S;if(!S.length)try{if(Wa[q]&&g instanceof Wa[q]||Object.prototype.toString.call(g)==="[object "+q+"]")return!0;if(g&&g.nodeType&&
1===g.nodeType){var Ib=null===(w=g.ownerDocument.defaultView)||void 0===w?void 0:w[q];if("function"===typeof Ib&&g instanceof Ib)return!0}}catch(Xb){}for(w=0;w<sa.length;w++)if(S=sa[w],"string"!==typeof S&&"number"!==typeof S&&"symbol"!==typeof S||!(S in g))return!1;return!!sa.length}function T(g,q,w,S){"undefined"===typeof S&&(S=da(q,!0));"boolean"===typeof S&&(S=da(q,S));g===Wa?u&&u(q,w,S):na&&Z(g,21)?Ua.call(g,q,w,S):g.addEventListener&&(g===Wa.document||g===Wa.document.documentElement?A.call(g,
q,w,S):u.call(g,q,w,S));S=!1;for(var G=hb.length;0<=--G;){var sa=hb[G];if(sa.object===g&&sa.event===q&&sa.H===w){S=!0;break}}S||hb.push({object:g,event:q,H:w})}function P(g,q,w,S){for(var G=hb.length;0<=--G;){var sa=hb[G];if(sa.object===g&&sa.event===q&&sa.H===w){hb.splice(G,1);break}}"undefined"===typeof S&&(S=da(q,!0));"boolean"===typeof S&&(S=da(q,S));g===Wa?t&&t(q,w,S):g.removeEventListener&&(g===Wa.document||g===Wa.document.documentElement?Q.call(g,q,w,S):t.call(g,q,w,S))}function da(g,q){var w=
!1;try{if(u&&ib.includes(g)){var S=Object.defineProperty({},"passive",{get:function(){w=!0}});u("test",$a,S)}}catch(G){}return w?{passive:!0,capture:q}:q}function Ja(){for(var g=hb,q=g.length;0<=--q;){var w=g[q];P(w.object,w.event,w.H)}hb=[]}function O(g){return"function"===typeof g&&/{\s+\[native code]/.test(Function.prototype.toString.call(g))}function ja(g,q){for(var w,S=[],G=2;G<arguments.length;G++)S[G-2]=arguments[G];return void 0!==Function.prototype.bind&&O(Function.prototype.bind)?(w=Function.prototype.bind).call.apply(w,
Ia([g,q],S,!1)):function(){for(var sa=0;sa<arguments.length;sa++);return g.apply(q,(S||[]).concat(Array.prototype.slice.call(arguments)||[]))}}function I(){if(kb){var g=new kb;if(Nb)for(var q=0,w=tb;q<w.length;q++){var S=w[q];void 0!==Nb[S]&&(g[S]=ja(Nb[S],g))}return g}return new Wa.XMLHttpRequest}function L(){document.cookie="".concat("__dTCookie","=").concat("1",";SameSite=Lax");var g=document.cookie.includes("__dTCookie");document.cookie="".concat("__dTCookie","=").concat("1","; expires=Thu, 01-Jan-1970 00:00:01 GMT");
return g}function ba(){return void 0===Wa.dialogArguments?navigator.cookieEnabled||L():L()}function W(){return Wa.dT_}function ia(g){g=encodeURIComponent(g);var q=[];if(g)for(var w=0;w<g.length;w++){var S=g.charAt(w);q.push(Dc[S]||S)}return q.join("")}function pa(g){g.includes("^")&&(g=g.split("^^").join("^"),g=g.split("^dq").join('"'),g=g.split("^rb").join(">"),g=g.split("^lb").join("<"),g=g.split("^p").join("|"),g=g.split("^e").join("="),g=g.split("^s").join(";"),g=g.split("^c").join(","),g=g.split("^bs").join("\\"));
return g}function wa(){return Ec}function db(g){Ec=g}function mb(g){var q=F("rid"),w=F("rpid");q&&(g.rid=q);w&&(g.rpid=w)}function Cb(g){if(g=g.xb){g=pa(g);try{Ec=new RegExp(g,"i")}catch(q){}}else Ec=void 0}function ec(g){return"n"===g||"s"===g||"l"===g?";SameSite=".concat(rc[g]):""}function qa(g,q,w){var S=1,G=0;do document.cookie=g+'=""'+(q?";domain="+q:"")+";path="+w.substring(0,S)+"; expires=Thu, 01 Jan 1970 00:00:01 GMT;",S=w.indexOf("/",S),G++;while(-1!==S&&5>G)}function Db(){var g=(document.domain||
location.hostname||"").split(".");return 1>=g.length?[]:g}function Pc(g,q){q="dTValidationCookieValue;path=/;domain=".concat(g).concat(ec(q));document.cookie="".concat(Nf(),"=").concat(q);return Ka(Nf())?(qa(Nf(),g,"/"),!0):!1}function kc(){if(Wa.MobileAgent||Wa.dynatraceMobile){var g=Qa("dtAdkSettings");return jb(g).privacyState||null}return null}function pb(g,q){return!Yb()||W().overloadPrevention&&!ha()?null:g.apply(this,q)}function Yb(){var g=kc();return 2===g||1===g?!1:!C("coo")||C("cooO")||
ha()}function Ob(g,q){try{Wa.sessionStorage.setItem(g,q)}catch(w){}}function tc(g,q){pb(Ob,[g,q])}function Rb(g){try{return Wa.sessionStorage.getItem(g)}catch(q){}return null}function cc(g){try{Wa.sessionStorage.removeItem(g)}catch(q){}}function fc(g){document.cookie=g+'="";path=/'+(F("domain")?";domain="+F("domain"):"")+"; expires=Thu, 01 Jan 1970 00:00:01 GMT;"}function Kb(g,q,w,S){q||0===q?(q=(q+"").replace(/[;\n\r]/g,"_"),g=g+"="+q+";path=/"+(F("domain")?";domain="+F("domain"):""),w&&(g+=";expires="+
w.toUTCString()),g+=ec(F("cssm")),S&&"https:"===location.protocol&&(g+=";Secure"),document.cookie=g):fc(g)}function Ab(g,q,w,S){pb(Kb,[g,q,w,S])}function Pb(g){return g.includes("v_4")?!0:!1}function nc(g){g=Ka(Hd(),g);g||((g=Rb(Hd()))&&Pb(g)?Eb(g):g="");return Pb(g)?g:""}function Eb(g){Ab(Hd(),g,void 0,C("ssc"))}function D(g){return(g=g||nc())?jb(g):{sessionId:"",serverId:"",overloadState:0,appState:{}}}function ra(g){return D(g).serverId}function Aa(g){return D(g).sessionId}function ha(){return navigator.userAgent.includes("RuxitSynthetic")}
function vb(g){var q={},w=0;for(g=g.split("|");w<g.length;w++){var S=g[w].split("=");2===S.length&&(q[S[0]]=decodeURIComponent(S[1].replace(/\+/g," ")))}return q}function qb(){var g=F("csu");return(g.indexOf("dbg")===g.length-3?g.substring(0,g.length-3):g)+"_"+F("app")+"_Store"}function Ya(g,q,w){void 0===q&&(q={});var S=0;for(g=g.split("|");S<g.length;S++){var G=g[S],sa=G,Ib=G.indexOf("=");-1===Ib?q[sa]="1":(sa=G.substring(0,Ib),q[sa]=G.substring(Ib+1,G.length))}!w&&(w=q,S=w.spc)&&(g=document.createElement("textarea"),
g.innerHTML=S,w.spc=g.value);return q}function x(g){var q;return null!==(q=ic[g])&&void 0!==q?q:Qc[g]}function C(g){g=x(g);return"false"===g||"0"===g?!1:!!g}function H(g){var q=x(g);q=parseInt(q);isNaN(q)&&(q=Qc[g]);return q}function F(g){return(x(g)||"")+""}function R(g,q){ic[g]=q+""}function E(g){return ic=g}function Fa(g){var q=ic[g];q&&(ic[g]=q.includes("#"+g.toUpperCase())?"":q)}function la(g){var q=g.agentUri;(null===q||void 0===q?0:q.includes("_"))&&(q=/([a-zA-Z]*)[0-9]{0,4}_([a-zA-Z_0-9]*)_[0-9]+/g.exec(q))&&
q.length&&2<q.length&&(g.csu=q[1],g.featureHash=q[2])}function Ea(g){var q=W().platformCookieOffset;if("number"===typeof q){a:{var w=F("cssm");var S=Db();if(S.length)for(q=S.slice(q);q.length;){if(Pc(q.join("."),w)){w=q.join(".");break a}q.shift()}w=""}w&&(g.domain=w)}else if(w=g.domain||"",q=(q=location.hostname)&&w?q===w||q.includes("."+w,q.length-("."+w).length):!0,!w||!q){g.domainOverride||(g.domainOriginal=g.domain||"",g.domainOverride="".concat(location.hostname,",").concat(w),delete g.domain);
a:{S=F("cssm");var G=Db().reverse();if(G.length)for(var sa=G[0],Ib=1;Ib<=G.length;Ib++){if(Pc(sa,S)){S=sa;break a}var Xb=G[Ib];Xb&&(sa="".concat(Xb,".").concat(sa))}S=""}S&&(g.domain=S);q||Xe.push({type:"dpi",severity:"Warning",text:'Configured domain "'.concat(w,'" is invalid for current location "').concat(location.hostname,'". Agent will use "').concat(g.domain,'" instead.')})}}function va(g,q){Ea(g);var w=ic.pVO;w&&(g.pVO=w);q||(g.bp=(g.bp||Qc.bp)+"")}function sb(){return ic}function wb(g){return Qc[g]===
x(g)}function jb(g){var q,w={},S={sessionId:"",serverId:"",overloadState:0,appState:w},G=g.split("_");if(2<G.length&&0===G.length%2){g=+G[1];if(isNaN(g)||3>g)return S;g={};for(var sa=2;sa<G.length;sa++){var Ib=G[sa];Ib.startsWith(cg)?w[Ib.substring(6).toLowerCase()]=+G[sa+1]:g[Ib]=G[sa+1];sa++}g.sn?(G=g.sn,G=G.length===Ce||12>=G.length?G:""):G="hybrid";S.sessionId=G;if(g.srv){a:{G=g.srv.replace("-2D","-");if(!isNaN(+G)&&(sa=parseInt(G),-99<=sa&&99>=sa))break a;G=""}S.serverId=G}G=+g.ol;1===G&&Bb(ha());
0<=G&&2>=G&&(S.overloadState=G);g=+g.prv;isNaN(g)||(S.privacyState=1>g||4<g?1:g);g=null===(q=F("app"))||void 0===q?void 0:q.toLowerCase();q=w[g];isNaN(q)||0!==q||Bb(ha())}return S}function Bb(g){var q=W();g||(q.disabled=!0,q.overloadPrevention=!0)}function Jb(){return Ic()}function rb(g,q){function w(){delete De[sa];g.apply(this,arguments)}for(var S=[],G=2;G<arguments.length;G++)S[G-2]=arguments[G];if("apply"in ld){S.unshift(w,q);var sa=ld.apply(Wa,S)}else sa=ld(w,q);De[sa]=!0;return sa}function Ub(g){delete De[g];
"apply"in Xc?Xc.call(Wa,g):Xc(g)}function Jc(g){Qe.push(g)}function Rc(g){for(var q=Qe.length;q--;)if(Qe[q]===g){Qe.splice(q,1);break}}function Tc(){return Qe}function Fc(g,q){return Ee(g,q)}function Ad(g){Nd(g)}function Mc(g,q){if(!sd||!re)return"";g=new sd([g],{type:q});return re(g)}function Wc(g,q){return Td?new Td(g,q):void 0}function td(g){"function"===typeof g&&Jh.push(g)}function ya(){return Jh}function J(){return vf}function ea(g){return function(){for(var q=[],w=0;w<arguments.length;w++)q[w]=
arguments[w];if("number"!==typeof q[0]||!De[q[0]])try{return g.apply(this,q)}catch(S){return g(q[0])}}}function Ba(){return Xe}function za(){Be=nb;Wa.performance&&(Ic=function(){return Math.round(Be()+Oa())});if(!Ic||isNaN(Ic())||0>=Ic()||!isFinite(Ic()))Ic=function(){return(new Date).getTime()}}function Da(){Ud&&(Wa.clearTimeout=Xc,Wa.clearInterval=Nd,Ud=!1)}function Ha(g,q){try{Wa.localStorage.setItem(g,q)}catch(w){}}function ka(g){try{Wa.localStorage.removeItem(g)}catch(q){}}function La(g){try{return Wa.localStorage.getItem(g)}catch(q){}return null}
function ob(g){Yb()?g():(Fe||(Fe=[]),Fe.push(g))}function Ra(){if(C("coo")&&!Yb()){for(var g=0,q=Fe;g<q.length;g++)rb(q[g],0);Fe=[];R("cooO",!0)}}function lb(){if(C("coo")&&Yb()){R("cooO",!1);fc(Hd());fc(Ye());fc(Kh());fc("dtAdk");fc(cd());fc(Yc());try{cc(zc()),cc(Yc()),ka(zc()),ka(Yc()),cc(cd()),cc(Hd()),ka(qb()),ka("dtAdk")}catch(g){}}}function gc(g,q){void 0===q&&(q=document.cookie||"");return q.split(g+"=").length-1}function Wb(g,q){var w=gc(g,q);if(1<w){q=F("domain")||Wa.location.hostname;var S=
Wa.location.hostname,G=Wa.location.pathname,sa=0,Ib=0;Vd.add(g);do{var Xb=S.substring(sa);if(Xb!==q||"/"!==G){qa(g,Xb===q?"":Xb,G);var jc=gc(g);jc<w&&(Vd.add(Xb),w=jc)}sa=S.indexOf(".",sa)+1;Ib++}while(0!==sa&&10>Ib&&1<w);F("domain")&&1<w&&qa(g,"",G)}}function Hb(){var g=document.cookie;Wb(Ye(),g);Wb(Hd(),g);Wb(Yc(),g);g=Vd.size;0<g&&g!==he&&(he=g,Xe.push({severity:"Error",type:"dcn",text:"Duplicate cookie name".concat(1!==g?"s":""," detected: ").concat(Array.from(Vd).join(","))}))}function dc(){Vd=
new Set;Hb();Jc(function(g,q,w,S){0===Vd.size||q||(g.av(S,"dCN",Array.from(Vd).join(",")),Vd.clear(),he=0)})}function Nc(g){var q=g,w=Math.pow(2,32);return function(){q=(1664525*q+1013904223)%w;return q/w}}function Sc(g,q){return isNaN(g)||isNaN(q)?Math.floor(33*ie()):Math.floor(ie()*(q-g+1))+g}function Uc(g){if(!g)return"";var q=Wa.crypto||Wa.msCrypto;if(q&&!navigator.userAgent.includes("Googlebot"))q=q.getRandomValues(new Uint8Array(g));else{q=[];for(var w=0;w<g;w++)q.push(Sc(0,32))}g=[];for(w=
0;w<q.length;w++){var S=Math.abs(q[w]%32);g.push(String.fromCharCode(S+(9>=S?48:55)))}return g.join("")}function be(){return Bd}function se(g){void 0===g&&(g=!0);wf=g}function Id(){var g=Wa.dT_;try{for(var q=Wa.parent;q&&q!==Wa;){var w=q.dT_,S;if(S=!!(w&&"ea"in w)&&"10297240712040816"===w.version){var G=g,sa=w,Ib=!G.bcv("ac")||G.scv("app")===sa.scv("app"),Xb=G.scv("postfix"),jc=sa.scv("postfix");S=Ib&&Xb===jc}if(S)return w.tdto();q=q!==q.parent?q.parent:void 0}}catch(Vc){}return g}function dd(g,q,
w){var S=H("pcl");S=g.length-S;0<S&&g.splice(0,S);S=ra(Ka(Hd(),w));for(var G=[],sa=S?"".concat(S,"$"):"",Ib=0;Ib<g.length;Ib++){var Xb=g[Ib];"-"!==Xb.D&&G.push("".concat(sa).concat(Xb.frameId,"h").concat(Xb.D))}g=G.join("p");g||(wf&&(Gc(!0,"a",w),se(!1)),g+="".concat(S,"$").concat(Bd,"h-"));g+="v".concat(q||ed(w));q=g+"e0";Ab(Ye(),q,void 0,C("ssc"))}function Cd(g,q){void 0===q&&(q=document.cookie);var w=Ka(Ye(),q);q=[];if(w&&"-"!==w){var S="";var G=0;for(w=w.split("p");G<w.length;G++){var sa=w[G],
Ib=S;void 0===Ib&&(Ib="");var Xb=sa.indexOf("h");var jc=sa.indexOf("v"),Vc=sa.indexOf("e");S=sa.substring(sa.indexOf("$")+1,Xb);Xb=-1!==jc?sa.substring(Xb+1,jc):sa.substring(Xb+1);Ib||-1===jc||(Ib=-1!==Vc?sa.substring(jc+1,Vc):sa.substring(jc+1));sa=null;(jc=g)||(jc=parseInt(S.split("_")[0]),Vc=Ic()%je,Vc<jc&&(Vc+=je),jc=jc+9E5>Vc);jc&&(sa={frameId:S,D:"-"===Xb?"-":parseInt(Xb),visitId:""});S=Ib;(Xb=sa)&&q.push(Xb)}for(g=0;g<q.length;g++)q[g].visitId=S}return q}function $c(g,q){var w=document.cookie;
q=Cd(q,w);for(var S=!1,G=0;G<q.length;G++){var sa=q[G];sa.frameId===Bd&&(sa.D=g,S=!0)}S||q.push({frameId:Bd,D:g,visitId:""});dd(q,void 0,w)}function ce(){return te}function ed(g){return Dd(g)||Gc(!0,"c",g)}function Dd(g){if(N(g)<=Ic())return Gc(!0,"t",g);var q=Ed(g);if(!q)return Gc(!0,"c",g);var w=Pg.exec(q);if(!w||3!==w.length||32!==w[1].length||isNaN(parseInt(w[2])))return Gc(!0,"i",g);tc(zc(),q);return q}function xd(g,q){var w=Ic();q=K(q).Oc;g&&(q=w);n(w+Wd+"|"+q);Ge()}function ke(g){var q="t"+
(Ic()-N(g));Gc(!0,q,g)}function Ed(g){var q,w;return null!==(w=null===(q=Cd(!0,g)[0])||void 0===q?void 0:q.visitId)&&void 0!==w?w:Rb(zc())}function Jd(){var g=Uc(Ce);try{g=g.replace(/[0-9]/g,function(q){return String.fromCharCode(Math.floor(2.5*parseInt(q)+65))})}catch(q){throw Z(q,7),q;}return g+"-0"}function yd(g,q){var w=Cd(!1,q);dd(w,g,q);tc(zc(),g);xd(!0)}function pd(g,q,w){return Gc(g,q,w)}function Gc(g,q,w){g&&(xf=!0);g=Ed(w);w=Jd();yd(w);if(Ed(document.cookie))for(var S=0,G=ue;S<G.length;S++)(0,G[S])(w,
xf,q,g);return w}function Od(g){ue.push(g)}function Ge(g){Ze&&Ub(Ze);Ze=rb(Kd,N(g)-Ic())}function Kd(){var g=document.cookie;if(N(g)<=Ic())return pb(ke,[g]),!0;ob(Ge);return!1}function n(g){var q=ja(Ab,null,Yc(),g,void 0,C("ssc"));q();var w=Ka(Yc());""!==w&&g!==w&&(Hb(),q(),g===Ka(Yc())||lh||(Xe.push({severity:"Error",type:"dcn",text:"Could not sanitize cookies"}),lh=!0));tc(Yc(),g)}function v(g,q){(q=Ka(g,q))||(q=Rb(g)||"");return q}function y(){var g=Dd()||"";tc(zc(),g);g=v(Yc());n(g);ka(zc());
ka(Yc())}function K(g){var q={Vd:0,Oc:0};if(g=v(Yc(),g))try{var w=g.split("|");2===w.length&&(q.Vd=parseInt(w[0]),q.Oc=parseInt(w[1]))}catch(S){}return q}function N(g){g=K(g);return Math.min(g.Vd,g.Oc+hf)}function Y(g){Wd=g}function ma(){var g=xf;xf=!1;return g}function xa(){Kd()||xd(!1)}function Sa(){var g=Ka(cd());g&&45===(null===g||void 0===g?void 0:g.length)||(g=La(cd())||Rb(cd()),45!==(null===g||void 0===g?void 0:g.length)&&(Qg=!0,g=Ic()+"",g+=Uc(45-g.length)));Ta(g);return g}function Ta(g){if(C("dpvc")||
C("pVO"))tc(cd(),g);else{var q=new Date;var w=q.getMonth()+Math.min(24,Math.max(1,H("rvcl")));q.setMonth(w);w=cd();pb(Ha,[w,g])}Ab(cd(),g,q,C("ssc"))}function ub(){return Qg}function Qb(g){var q=Ka(cd());fc(cd());cc(cd());ka(cd());R("pVO",!0);Ta(q);g&&pb(Ha,["dt-pVO","1"]);y()}function Kc(){ka("dt-pVO");C("pVO")&&(R("pVO",!1),Sa());cc(cd());y()}function lc(g,q,w,S,G){var sa=document.createElement("script");sa.setAttribute("src",g);q&&sa.setAttribute("defer","defer");w&&(sa.onload=w);S&&(sa.onerror=
S);G&&sa.setAttribute("id",G);sa.setAttribute("crossorigin","anonymous");g=document.getElementsByTagName("script")[0];g.parentElement.insertBefore(sa,g)}function gd(g,q){return dg+"/"+(q||Re)+"_"+g+"_"+(H("buildNumber")||W().version)+".js"}function zd(){var g,q;try{null===(q=null===(g=Wa.MobileAgent)||void 0===g?void 0:g.incrementActionCount)||void 0===q?void 0:q.call(g)}catch(w){}}function Pd(){var g,q=Wa.dT_;Wa.dT_=(g={},g.di=0,g.version="10297240712040816",g.cfg=q?q.cfg:"",g.iCE=q?ba:function(){return navigator.cookieEnabled},
g.ica=1,g.disabled=!1,g.disabledReason="",g.overloadPrevention=!1,g.gAST=J,g.ww=Wc,g.stu=Mc,g.nw=Jb,g.st=rb,g.si=Fc,g.aBPSL=Jc,g.rBPSL=Rc,g.gBPSL=Tc,g.aBPSCC=td,g.gBPSCC=ya,g.buildType="dynatrace",g.gSSV=Rb,g.sSSV=tc,g.rSSV=cc,g.rvl=ka,g.iVSC=Pb,g.p3SC=jb,g.dC=fc,g.sC=Ab,g.esc=ia,g.gSId=ra,g.gDtc=Aa,g.gSC=nc,g.sSC=Eb,g.gC=Qa,g.cRN=Sc,g.cRS=Uc,g.cfgO=sb,g.pCfg=vb,g.pCSAA=Ya,g.cFHFAU=la,g.sCD=va,g.bcv=C,g.ncv=H,g.scv=F,g.stcv=R,g.rplC=E,g.cLSCK=qb,g.gFId=be,g.gBAU=gd,g.iS=lc,g.eWE=ob,g.oEIEWA=pb,g.eA=
Ra,g.dA=lb,g.iNV=ub,g.gVID=Sa,g.dPV=Qb,g.ePV=Kc,g.sVIdUP=se,g.sVTT=Y,g.sVID=yd,g.rVID=Dd,g.gVI=ed,g.gNVIdN=pd,g.gARnVF=ma,g.cAUV=xa,g.uVT=xd,g.aNVL=Od,g.gPC=Cd,g.cPC=$c,g.sPC=dd,g.clB=Da,g.ct=Ub,g.aRI=mb,g.iXB=Cb,g.gXBR=wa,g.sXBR=db,g.de=pa,g.cCL=Pa,g.iEC=zd,g.rnw=Oa,g.gto=gb,g.ael=T,g.rel=P,g.sup=da,g.cuel=Ja,g.iAEPOO=Yb,g.iSM=ha,g.gxwp=I,g.iIO=Z,g.prm=Ma,g.cI=Ad,g.gidi=Ba,g.iDCV=wb,g.gCF=Ka,g.gPSMB=kc,g.lvl=La,g.gCP=(null===q||void 0===q?0:q.platformPrefix)?function(){return q.platformPrefix||""}:
void 0,g.platformCookieOffset=null===q||void 0===q?void 0:q.platformCookieOffset,g.tdto=Id,g.gFLAI=ce,g)}function md(){if(C("nsfnv")){var g=Ka(Hd());if(!g.includes("".concat($e,"-"))){var q=jb(g).serverId;g=g.replace("".concat($e).concat(q),"".concat($e).concat("".concat(-1*Sc(2,99)).replace("-","-2D")));Eb(g)}}}function Fd(){ob(function(){if(!Aa()){var g=-1*Sc(2,99),q=Uc(Ce);Eb("v_4".concat($e).concat("".concat(g).replace("-","-2D"),"_sn_").concat(q))}});Od(md)}function He(){for(var g=[],q=0;q<arguments.length;q++)g[q]=
arguments[q];Wa.console.log.apply(Wa.console,g)}this.dT_&&dT_.prm&&dT_.prm();var Wa="undefined"!==typeof globalThis?globalThis:"undefined"!==typeof window?window:void 0,eg;(function(g){g[g.ENABLED=0]="ENABLED";g[g.DISABLED=1]="DISABLED";g[g.DELAYED=2]="DELAYED"})(eg||(eg={}));var Of;(function(g){g[g.BLOCKED_BY_PERCENTAGE=0]="BLOCKED_BY_PERCENTAGE";g[g.ENABLED=1]="ENABLED";g[g.BLOCKED=2]="BLOCKED"})(Of||(Of={}));var jf;(function(g){g[g.NONE=1]="NONE";g[g.OFF=2]="OFF";g[g.PERFORMANCE=3]="PERFORMANCE";
g[g.BEHAVIOR=4]="BEHAVIOR"})(jf||(jf={}));var zg;(function(g){g.OVERLOAD_PREVENTION="ol";g.PRIVACY_STATE="prv";g.SERVER_ID="srv";g.SESSION_ID="sn"})(zg||(zg={}));var Se;(function(g){g.DYNATRACE_MOBILE="dynatraceMobile";g.MOBILE_AGENT="MobileAgent"})(Se||(Se={}));var Ag;(function(g){g[g.ARRAY=0]="ARRAY";g[g.BOOLEAN=1]="BOOLEAN";g[g.NUMBER=2]="NUMBER";g[g.STRING=3]="STRING";g[g.FUNCTION=4]="FUNCTION";g[g.OBJECT=5]="OBJECT";g[g.DATE=6]="DATE";g[g.ERROR=7]="ERROR";g[g.ELEMENT=8]="ELEMENT";g[g.HTML_ELEMENT=
9]="HTML_ELEMENT";g[g.HTML_IMAGE_ELEMENT=10]="HTML_IMAGE_ELEMENT";g[g.PERFORMANCE_ENTRY=11]="PERFORMANCE_ENTRY";g[g.PERFORMANCE_TIMING=12]="PERFORMANCE_TIMING";g[g.PERFORMANCE_RESOURCE_TIMING=13]="PERFORMANCE_RESOURCE_TIMING";g[g.PERFORMANCE_NAVIGATION_TIMING=14]="PERFORMANCE_NAVIGATION_TIMING";g[g.CSS_RULE=15]="CSS_RULE";g[g.CSS_STYLE_SHEET=16]="CSS_STYLE_SHEET";g[g.REQUEST=17]="REQUEST";g[g.RESPONSE=18]="RESPONSE";g[g.SET=19]="SET";g[g.MAP=20]="MAP";g[g.WORKER=21]="WORKER";g[g.XML_HTTP_REQUEST=
22]="XML_HTTP_REQUEST";g[g.SVG_SCRIPT_ELEMENT=23]="SVG_SCRIPT_ELEMENT";g[g.HTML_META_ELEMENT=24]="HTML_META_ELEMENT";g[g.HTML_HEAD_ELEMENT=25]="HTML_HEAD_ELEMENT";g[g.ARRAY_BUFFER=26]="ARRAY_BUFFER";g[g.SHADOW_ROOT=27]="SHADOW_ROOT"})(Ag||(Ag={}));var bg=-1,Ye=fb("dtPC"),Hd=fb("dtCookie"),Yc=fb("rxvt"),cd=fb("rxVisitor"),Nf=fb("dTValidationCookie"),Kh=fb("dtSa"),qe,Be,af=setTimeout;fa.prototype["catch"]=function(g){return this.then(null,g)};fa.prototype.then=function(g,q){var w=new this.constructor(xb);
oa(this,new X(g,q,w));return w};fa.prototype["finally"]=function(g){var q=this.constructor;return this.then(function(w){return q.resolve(g()).then(function(){return w})},function(w){return q.resolve(g()).then(function(){return q.reject(w)})})};fa.all=function(g){return new fa(function(q,w){function S(Xb,jc){try{if(jc&&("object"===typeof jc||"function"===typeof jc)){var Vc=jc.then;if("function"===typeof Vc){Vc.call(jc,function(kf){S(Xb,kf)},w);return}}G[Xb]=jc;0===--sa&&q(G)}catch(kf){w(kf)}}if(!g||
"undefined"===typeof g.length)return w(new TypeError("Promise.all accepts an array"));var G=Array.prototype.slice.call(g);if(0===G.length)return q([]);for(var sa=G.length,Ib=0;Ib<G.length;Ib++)S(Ib,G[Ib])})};fa.allSettled=function(g){return new this(function(q,w){function S(Ib,Xb){if(Xb&&("object"===typeof Xb||"function"===typeof Xb)){var jc=Xb.then;if("function"===typeof jc){jc.call(Xb,function(Vc){S(Ib,Vc)},function(Vc){G[Ib]={status:"rejected",reason:Vc};0===--sa&&q(G)});return}}G[Ib]={status:"fulfilled",
value:Xb};0===--sa&&q(G)}if(!g||"undefined"===typeof g.length)return w(new TypeError(typeof g+" "+g+" is not iterable(cannot read property Symbol(Symbol.iterator))"));var G=Array.prototype.slice.call(g);if(0===G.length)return q([]);var sa=G.length;for(w=0;w<G.length;w++)S(w,G[w])})};fa.resolve=function(g){return g&&"object"===typeof g&&g.constructor===fa?g:new fa(function(q){q(g)})};fa.reject=function(g){return new fa(function(q,w){w(g)})};fa.race=function(g){return new fa(function(q,w){if(!g||"undefined"===
typeof g.length)return w(new TypeError("Promise.race accepts an array"));for(var S=0,G=g.length;S<G;S++)fa.resolve(g[S]).then(q,w)})};fa.Hb="function"===typeof setImmediate&&function(g){setImmediate(g)}||function(g){af(g,0)};fa.vc=function(g){"undefined"!==typeof console&&console&&console.warn("Possible Unhandled Promise Rejection:",g)};var ae=fa,Qd;(function(g){g.ANCHOR="A";g.BUTTON="BUTTON";g.FORM="FORM";g.I_FRAME="IFRAME";g.IMAGE="IMG";g.INPUT="INPUT";g.LABEL="LABEL";g.LINK="LINK";g.OPTION="OPTION";
g.SCRIPT="SCRIPT";g.SELECT="SELECT";g.STYLE="STYLE";g.TEXT_AREA="TEXTAREA"})(Qd||(Qd={}));var u,t,A,Q,na=Wa.Worker,Ua=na&&na.prototype.addEventListener,hb=[],ib=["touchstart","touchend","scroll"],kb,tb="abort getAllResponseHeaders getResponseHeader open overrideMimeType send setRequestHeader".split(" "),Nb,Dc={"!":"%21","~":"%7E","*":"%2A","(":"%28",")":"%29","'":"%27",$:"%24",";":"%3B",",":"%2C"},Ec,Cc,rc=(Cc={},Cc.l="Lax",Cc.s="Strict",Cc.n="None",Cc),Qc,Ce=32,Xd;(function(g){g.LAX="l";g.NONE="n";
g.NOT_SET="0";g.STRICT="s"})(Xd||(Xd={}));var zc=fb("rxvisitid"),ic={},cg="app-3A",Td=Wa.Worker,sd=Wa.Blob,re=Wa.URL&&Wa.URL.createObjectURL,Xc,Nd,ld,Ee,Ud=!1,Qe,Jh=[],Xe=[],vf,yf,De={},Ic,Fe=[],Vd,he=0,ie,lf,Bd,je=6E8,wf=!1,te,Pg=/([A-Z]+)-([0-9]+)/,ue=[],Wd,hf,xf=!1,Ze,lh=!1,Qg=!1,zf,dg,Re,$e="".concat("_","srv").concat("_");(function(){var g,q,w;if(!("documentMode"in document)||isNaN(document.documentMode)){var S=!(null===(q=navigator.userAgent)||void 0===q?0:q.includes("RuxitSynthetic"));if(!Wa.dT_||
!Wa.dT_.cfg||"string"!==typeof Wa.dT_.cfg||"initialized"in Wa.dT_&&Wa.dT_.initialized)(null===(w=Wa.dT_)||void 0===w?0:w.gCP)?He("[CookiePrefix/initCode] initCode with cookie prefix already initialized, not initializing initCode!"):He("InitConfig not found or agent already initialized! This is an injection issue."),Wa.dT_&&(Wa.dT_.di=3);else if(S)try{Pd();var G;Qc=(G={},G.ade="",G.aew=!0,G.apn="",G.agentLocation="",G.agentUri="",G.app="",G.ac=!0,G.async=!1,G.ase=!1,G.auto=!1,G.bp=3,G.bs=!1,G.buildNumber=
0,G.csprv=!0,G.cepl=16E3,G.cls=!0,G.ccNcss=!1,G.coo=!1,G.cooO=!1,G.cssm="0",G.cwtDomains="",G.cwtUrl="w2dax4xgw3",G.cwt="",G.cors=!1,G.csu="",G.cuc="",G.cce=!1,G.cux=!1,G.postfix="",G.dataDtConfig="",G.debugName="",G.dvl=500,G.dASXH=!1,G.disableCookieManager=!1,G.dKAH=!1,G.disableLogging=!1,G.dmo=!1,G.doel=!1,G.dpch=!1,G.dpvc=!1,G.disableXhrFailures=!1,G.domain="",G.domainOverride="",G.domainOriginal="",G.doNotDetect="",G.ds=!0,G.dsndb=!1,G.dsa=!1,G.dsss=!1,G.dssv=!0,G.earxa=!0,G.exp=!1,G.eni=!0,
G.expw=!1,G.instr="",G.evl="",G.fa=!1,G.fvdi=!1,G.featureHash="",G.hvt=216E5,G.imm=!1,G.ign="",G.iub="",G.iqvn=!1,G.initializedModules="",G.lastModification=0,G.lupr=!0,G.lab=!1,G.legacy=!1,G.lt=!0,G.mb="",G.md="",G.mdp="",G.mdl="",G.mcepsl=100,G.mdn=5E3,G.mhl=4E3,G.mpl=1024,G.mmds=2E4,G.msl=3E4,G.bismepl=2E3,G.mel=200,G.mepp=10,G.moa=30,G.mrt=3,G.ntd=!1,G.nsfnv=!1,G.ncw=!1,G.oat=180,G.ote=!1,G.owasp=!1,G.pcl=20,G.pt=!0,G.perfbv=1,G.prfSmpl=0,G.pVO=!1,G.peti=!1,G.raxeh=!0,G.rdnt=0,G.nosr=!0,G.reportUrl=
"dynaTraceMonitor",G.rid="",G.ridPath="",G.rpid="",G.rcdec=12096E5,G.rtl=0,G.rtp=2,G.rtt=1E3,G.rtu=200,G.rvcl=24,G.sl=100,G.ssc=!1,G.svNB=!1,G.srad=!0,G.srbbv=1,G.srbw=!0,G.srdinitrec=!0,G.srmr=100,G.srms="1,1,,,",G.srsr=1E5,G.srtbv=3,G.srtd=1,G.srtr=500,G.srvr="",G.srvi=0,G.srwo=!1,G.srre="",G.srxcss=!0,G.srxicss=!0,G.srficros=!0,G.srmrc=!1,G.srsdom=!0,G.srfirrbv=!0,G.srcss=!0,G.srmcrl=1,G.srmcrv=10,G.st=3E3,G.spc="",G.syntheticConfig=!1,G.tal=0,G.tt=100,G.tvc=3E3,G.uxdce=!1,G.uxdcw=1500,G.uxrgce=
!0,G.uxrgcm="100,25,300,3;100,25,300,3",G.uam=!1,G.uana="data-dtname,data-dtName",G.uanpi=0,G.pui=!1,G.usrvd=!0,G.vrt=!1,G.vcfi=!0,G.vcsb=!1,G.vcit=1E3,G.vct=50,G.vcx=50,G.vscl=0,G.vncm=1,G.vrei="",G.xb="",G.chw="",G.xt=0,G.xhb="",G);var sa;Ma();var Ib;kb=Wa.XMLHttpRequest;var Xb=null===(Ib=Wa.XMLHttpRequest)||void 0===Ib?void 0:Ib.prototype;if(Xb)for(Nb={},q=0,w=tb;q<w.length;q++){var jc=w[q];void 0!==Xb[jc]&&(Nb[jc]=Xb[jc])}u=Wa.addEventListener;t=Wa.removeEventListener;A=Wa.document.addEventListener;
Q=Wa.document.removeEventListener;ld=Wa.setTimeout;Ee=Wa.setInterval;Ud||(Xc=Wa.clearTimeout,Nd=Wa.clearInterval);var Vc=ba?ba():navigator.cookieEnabled,kf=1===jb(Ka("dtAdkSettings")||(null===(sa=yf)||void 0===sa?void 0:sa.getItem("dtAdkSettings"))||"").overloadState;Pa();if(!(!Vc||kf?0:"complete"!==document.readyState||Wa.performance&&Wa.performance.timing))throw Error("Error during initCode initialization");try{yf=Wa.localStorage}catch(Lh){}Xe=[];za();vf=Ic();Qe=[];De={};Ud||(Wa.clearTimeout=ea(Xc),
Wa.clearInterval=ea(Nd),Ud=!0);var ve=Math.random(),we=Math.random();lf=0!==ve&&0!==we&&ve!==we;if(navigator.userAgent.includes("Googlebot")){var Yd=performance.getEntriesByType("navigation")[0];sa=1;if(Yd){for(var mf in Yd){var Pf=Yd[mf];"number"===typeof Pf&&Pf&&(sa=1===sa?Pf:sa+Pf)}var Af=Math.floor(1E4*sa)}else Af=sa;ie=Nc(Af)}else lf?ie=Math.random:ie=Nc(Ic());Bd=vf%je+"_"+parseInt(Sc(0,1E3)+"");a:{var Rd,Te,ud=W().cfg;ic={reportUrl:"dynaTraceMonitor",initializedModules:"",csu:"dtagent",dataDtConfig:"string"===
typeof ud?ud:""};W().cfg=ic;ic.csu="ruxitagentjs";var Ie=ic.dataDtConfig;Ie&&!Ie.includes("#CONFIGSTRING")&&(Ya(Ie,ic),Fa("domain"),Fa("auto"),Fa("app"),la(ic));var Ld=document.getElementsByTagName("script"),Qf=Ld.length,nf=(ic.dataDtConfig||"").includes("#CONFIGSTRING")?null:ic;if(0<Qf)for(Af=0;Af<Qf;Af++)b:{Yd=void 0;var Rg=Ld[Af];mf=nf;if(Rg.attributes){Pf=mf;var qi=Rg.src,mh=Rg.attributes.getNamedItem("data-dtconfig");if(mh){ud=void 0;Ie=qi;var Mh=mh.value;sa={};ic.legacy="1";Xb=/([a-zA-Z]*)_([a-zA-Z_0-9]*)_([0-9]+)/g;
Ie&&(ud=Xb.exec(Ie),null===ud||void 0===ud?0:ud.length)&&(sa.csu=ud[1],sa.featureHash=ud[2],sa.agentLocation=Ie.substring(0,Ie.indexOf(ud[1])-1),sa.buildNumber=ud[3]);if(Mh){Ya(Mh,sa,!0);var nh=sa.agentUri;!Ie&&nh&&(ud=Xb.exec(nh),null===ud||void 0===ud?0:ud.length)&&(sa.csu=ud[1])}Ea(sa);Yd=sa;if(!mf)Pf=Yd;else if(!Yd.syntheticConfig){nf=Yd;break b}}nf=Pf}else nf=mf}if(nf)for(var fg in nf)if(Object.prototype.hasOwnProperty.call(nf,fg)){Ld=fg;var de=nf[Ld];"undefined"!==typeof de&&(ic[Ld]=de)}var fd=
qb();try{var Sd=(nf=yf)&&nf.getItem(fd);if(Sd){var ee=vb(Sd),Md=Ya(ee.config||""),Rf=ic.lastModification||"0",oh=parseInt((Md.lastModification||ee.lastModification||"0").substring(0,13)),Nh="string"===typeof Rf?parseInt(Rf.substring(0,13)):Rf;if(!Rf||oh>=Nh)if(Md.csu=ee.name||F("csu"),Md.featureHash=ee.featureHash||F("featureHash"),Md.agentUri&&la(Md),va(Md,!0),Cb(Md),mb(Md),oh>(+ic.lastModification||0)){var bf=C("auto"),gg=C("legacy");ic=E(Md);ic.auto=bf?"1":"0";ic.legacy=gg?"1":"0"}}}catch(Lh){}va(ic);
try{var Sg=ic.ign;if(Sg&&(new RegExp(Sg)).test(Wa.location.href)){delete Wa.dT_;var le=!1;break a}}catch(Lh){}if(ha()){var Bf=navigator.userAgent,Je=Bf.lastIndexOf("RuxitSynthetic");if(-1===Je)var Cf={};else{var of=Bf.substring(Je+14);if(of.includes(" c")){fd={};Sd=0;for(var Bg=of.split(" ");Sd<Bg.length;Sd++){var Tg=Bg[Sd];if(Tg.startsWith("c")){var ph=Tg.substring(1),qh=ph.indexOf("="),Oh=ph.substring(0,qh),Ug=ph.substring(qh+1);Oh&&Ug&&(fd[Oh]=Ug)}}Cf=fd}else Cf={}}of=void 0;for(of in Cf)if(Object.prototype.hasOwnProperty.call(Cf,
of)&&Cf[of]){var Cg=Cf[of];"undefined"!==typeof Cg&&(ic[of]=Cg)}E(ic)}var Ke=null===(Te=(Rd=W()).gCP)||void 0===Te?void 0:Te.call(Rd),Dg=F("cuc");if(Ke&&Ke!==Dg)throw Error("platformPrefix and cuc do not match!");le=!0}if(!le)throw Error("Error during config initialization");dc();zf=W().disabled;var Zd;if(!(Zd=F("agentLocation")))a:{var Ph=F("agentUri");if(Ph||document.currentScript){var Le=Ph||document.currentScript.src;if(Le){var rh=Le.includes("_complete")?2:1,Eg=Le.lastIndexOf("/");for(le=0;le<
rh&&-1!==Eg;le++)Le=Le.substring(0,Eg),Eg=Le.lastIndexOf("/");Zd=Le;break a}}var Vg=location.pathname;Zd=Vg.substring(0,Vg.lastIndexOf("/"))}dg=Zd;Re=F("csu")||"ruxitagentjs";"true"!==Ka("dtUseDebugAgent")||Re.includes("dbg")||(Re=F("debugName")||Re+"dbg");if(!C("auto")&&!C("legacy")&&!zf){var Sf=F("agentUri")||gd(F("featureHash"));if(C("async")||"complete"===document.readyState)lc(Sf,C("async"),void 0,void 0,"dtjsagent");else{var Tf="".concat("dtjsagent","dw");document.write('<script id="'.concat(Tf,
'" type="text/javascript" src="').concat(Sf,'">\x3c/script>'));document.getElementById(Tf)||lc(Sf,C("async"),void 0,void 0,"dtjsagent")}}Ka(Hd())&&R("cooO",!0);Fd();R("pVO",!!La("dt-pVO"));ob(Sa);Wd=18E5;hf=H("hvt")||216E5;var $i=Id();te=void 0;$i&&"ea"in $i&&(te=$i.gITAID());pb($c,[te||1])}catch(Lh){"platformPrefix and cuc do not match!"===Lh.message?(Zd=Wa.dT_,Wa.dT_=(g={},g.minAgentVersion=Zd.minAgentVersion,g.platformPrefix=Zd.platformPrefix,g.platformCookieOffset=Zd.platformCookieOffset,g),He("[CookiePrefix/initCode] cuc and platformPrefix do not match, disabling agent!")):
(delete Wa.dT_,He("JsAgent initCode initialization failed!",Lh))}}})()})();
